LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;

ENTITY MUX2X1 IS
  GENERIC (width : INTEGER);
  PORT (
    i_in0, i_in1 : IN STD_LOGIC_VECTOR (width - 1 DOWNTO 0);
    i_sel : IN STD_LOGIC;
    o_out : OUT STD_LOGIC_VECTOR (width - 1 DOWNTO 0)
  );
END MUX2X1;

ARCHITECTURE RTL OF MUX2X1 IS
BEGIN
  o_out <= i_in0 WHEN i_sel = '0' ELSE
    i_in1;
END ARCHITECTURE RTL;